### ISSUE TITLE
Error messages during uploads are not shown to the user

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#12]
This seems to be mainly affecting Firefox.

When an invalid file is uploaded, the error message is not shown to the user.

**Comment by EliotRagueneau** [comment]
https://stackoverflow.com/questions/25275675/gwt-onsubmitcomplete-not-fired-in-firefox
Caused by this issue, but no answer under this post ...

**Comment by EliotRagueneau** [comment]
Okay so I found the exact reason, and it is more or less in your side yes:
In Firefox, GWT doesn't consider a content-type of "application/problem+json" as a possible answer to the form submission that we are doing. I don't know if this is the same everywhere, but when you use 
```python 
resp = make_response(json.dumps({
    "detail": "Failed to detect used delimiter",
    "status": 500,
    "title": "Internal Server Error",
    "type": "about:blank"
}), 500)
resp.headers["Content-Type"] = "application/json"
return resp
```
instead of 
```python
abort(500, "Failed to detect used delimiter")
```
then it works. 

You can probably make a fancy custom abort function to simplify all that but I tested locally and it works.
In terms of the json we are expecting, we really need the status and the detail, the title is only used in the console as a debug message (normally), and we don't use the type.

I only tested this with a file with no delimiters so that the only abort of /upload that I tested, but I guess the problem is the same with the other abort, at least of this function.

Regarding the other usages, if you want I can give you all the endpoints where we handle these "GSAError", to know where you might need to replace the abort functions.

Another solution might be to configure flask so that it provides a simpler content-type whenever you abort, but I don't know flask enough to be sure that it's possible :smile:

**Comment by EliotRagueneau** [comment]
In a more compact fashion
```python
abort(Response({"detail": 'Failed to detect used delimiter', "status": 500}, content_type="application/json", status=500))
```

**Comment by jgriss** [comment]
This should now be fixed in both the dev and the prod version.
