### ISSUE TITLE
Classical download options to not represent ReactomeGSA results

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#13]
The default download options ("old" PDF report and CSV file) do not match the ReactomeGSA results.

These should be hidden in the UI for ReactomeGSA results

**Comment by EliotRagueneau** [comment]
According to Gui's commit (who has left now), he reintegrated those download options since endpoint has been fixed. I guess he was speaking about the mismatch with GSA results. Are you sure there are still mismatches? If yes, wouldn't it be better to fix those rather than completely remove the pdf and the csv option, especially since they do not provide the same information as the GSA report?

**Comment by jgriss** [comment]
Hi @EliotRagueneau,

There must have been a misunderstanding. In the context of a ReactomeGSA analysis, these results are not applicable (not to say they are wrong).

The only valid download files (next to the plots) are the reports generated by ReactomeGSA.

![image](https://user-images.githubusercontent.com/10997605/142932327-89d8b096-6271-4e1b-a9f0-f29478f4dff3.png)

At the moment, only the first three are valid. The p-values / FDR values in the other "standard" files are all incorrect.

Kind regards,
Johannes

**Comment by EliotRagueneau** [comment]
Fix deployed at https://dev.reactome.org/PathwayBrowser/#/TOOL=AT

**Comment by jgriss** [comment]
Great! Thanks a lot!
